on: 
  issues:
    types:
      - closed
jobs:
  unassign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get assignees
        id: get
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/assignees
        env:
          GITHUB_TOKEN: ${{ secrets.GHTESTER }}
      - name: Print assignees
        run: echo "${{ steps.get.outputs.data.*.login }}"  
