name: Build and publish a Docker image

on:
  push:
    tags:
      - '*'
  release:  
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: get existing labels
        id: getlabels

        run: |
          export existing_labels=$(cat Dockerfile | grep LABEL | sed -E 's/^LABEL\s+//g' | jq -Rsc 'split("\n")[:-1]')
          echo $existing_labels
          echo "existing_labels=$existing_labels" >> $GITHUB_OUTPUT
      - name: echo labels
        run: |
          echo "${{ steps.getlabels.outputs.existing_labels }}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
          labels: |
            ${{ fromJson(steps.getlabels.outputs.existing_labels.*) }}
          # sep-labels: '%0A'

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: echo labels
        run: echo "${{ toJson(steps.meta.outputs.labels) }}" 
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
