# This is a basic workflow to help you get started with Actions

name: "branch create"

# Controls when the workflow will run
on: 
  create:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.ref_type == 'branch'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: parse-issue-num
        run: echo "num=$(echo ${{ github.ref_name }}  | grep -E '^[0-9]+-' | cut -d '-' -f 1)" >> $GITHUB_OUTPUT
      - name: Print parsed issue num
        run: echo "${{ steps.parse-issue-num.outputs.num }}"
      - name: Reopen issue
        id: reopen
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/issues/${{ steps.parse-issue-num.outputs.num }}
          state: 'open'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Assign issue
        id: assign
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/issues/${{ steps.parse-issue-num.outputs.num }}/assignees
          assignees: '[ ${{ github.actor }} ]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
