name: Scheduled regeneration
on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        description: 'The repository to generate data for'
      tag:
        required: true
        description: 'The tag to generate data for'

concurrency:
  group: scheduled-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    name: 'pull metadata from app repo and generate json and html'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out publisher repository
      - name: Check out target app repository
      - name: setup python 
      - name: install clams sdk 
      - name: generate app metadata (dir = app repo -> metadata.json file)
      - name: prep envvar for shortname and version
      - name: generate html of app metadata 
      - name: copy html and json to proper location
      - name: append app metadata to BIG json for API access
      - name: commit docs and push to new branch
      - name: start a new pr
